package com.example.spens.mad_lib_design_2

var array_presskonferens = arrayOf("Namn på en tecknad figur", "Tidsenhet", "Beskrivning på en person","Siffra", "Mätenhet", "Färg","Siffra","Tidsenhet","Geografisk plats", "Substantiv", "Kroppsdel","Namn på känd person","Högtid","Årtal","Namn på känd plats", "Substantiv i singular", "Kroppsdel i best.form","Siffra","Historisk person", "Resturang", "Siffra","Tidsenhet","")
var textStory_presskonferens = "God kväll, jag heter " + array_presskonferens[0] + " och är huvudansvarig för denna mordutredning. Jag och mitt team har arbetat i många " + array_presskonferens[1] + " för att få fram en " + array_presskonferens[2] + " och bra beskrivning på mördaren. Det vi i nuläget vet är att mördaren antagligen är " + array_presskonferens[3] + "  " + array_presskonferens[4] + " lång, har " + array_presskonferens[5] + " hårfärg, är cirka " + array_presskonferens[6] + " "  + array_presskonferens[7] + " gammal, bor i " + array_presskonferens[8] + " och har av vittnen blivit sedd ha en " + array_presskonferens[9] + " hängandes kring sin " + array_presskonferens[10] + ". Vi har kommit fram till att mordet på " + array_presskonferens[11] + " ägt rum på " + array_presskonferens[12] + " " + array_presskonferens[13] + ". Brottet skedde i " + array_presskonferens[14] + ". Vapnet som mördaren ska ha använt var en/ett " + array_presskonferens[15] + ". Vapnet ska ha använts på så sätt att mördaren slog offret 10 gånger på " + array_presskonferens[16] + " vilket tillslut ledde till offrets död. Vi har just nu " + array_presskonferens[17] + " bevis som pekar på att brottet har begåtts av " + array_presskonferens[18] + ". Dock behöver vi ännu mer bevis för att vara säkra. Vi har ännu inte hittat brottslingen men enligt en trovärdig källa besöker mördaren " + array_presskonferens[19] + " " + array_presskonferens[20] + " gånger varje " + array_presskonferens[21] + ". Så vi räknar med ett gripande inom kort. Tack för mig!"


var array_jobbintervju = arrayOf(" Skådespelare","Namn på en historisk figur","Typ av arbete","Något du säger när du är i knipa","Typ av spel","Yrke man hade förr i tiden","Tidsspann","Namn på företag","Siffra","Valuta","Något du säger när du blir chockad","Adjektiv","Siffra"," Badrumsartikel i plural","Djur i plural","Typ av släkting","Namn","Siffra","Substantiv i plural","Siffra","Kroppsdel: best form"," Tidsspan","Låt","")
var textStory_jobbintervju = "Intervjuare: " + array_jobbintervju[0] + " Jobbsökande " + array_jobbintervju[1]+ " Så... du vill alltså börja jobba som: " + array_jobbintervju[2] + " Vad har du för kvalifikationer för detta arbete? " + array_jobbintervju[3] + " Ehm, jag är väldigt bra på " + array_jobbintervju[4] +  ", jag har även jobbat som "+ array_jobbintervju[5] + " i " + array_jobbintervju[6] + ". Oj, ja det är väldigt bra meriter. Men varför vill du ta detta arbete. Jag vill ta jobbet för att jag är skyldig " + array_jobbintervju[7] + array_jobbintervju[8] + array_jobbintervju[9]+". " + array_jobbintervju[10] +" .Du är verkligen i en " + array_jobbintervju[11] + " knipa. Hur satte du dig i den positionen? Jag köpte " + array_jobbintervju[12] + array_jobbintervju[13] +" och jag köpte 10 000 " + array_jobbintervju[14]+" till min "+ array_jobbintervju[15]+ " " + array_jobbintervju[16] + ". Jaha, ja om du får detta jobb är din lön på en bra bit över "+ array_jobbintervju[17] +" "+ array_jobbintervju[18]+ " i månaden. Det borde täcka alla dina skulder. Jag måste som chef också informera dig om att ungefär " + array_jobbintervju[19] + " procent av de anställda skadar " + array_jobbintervju[20] + " varje år. Ser du detta som ett problem? Det är inget problem för mig, jag opererade bort den för " + array_jobbintervju[21] +" sedan. Okej, då är jobbet ditt, om du bara kan svara på en fråga till. Sjung en bit från låten " + array_jobbintervju[22] +". “Sjung”... Okej grattis du får jobbet!";


var array_julspecial = arrayOf("konstigt efternamn","film/serie","ovanligt namm","Substantiv i singular","klädesplagg","ovanlig maträt","siffra","tidsenhet","möbel","siffra","Tysk förnamn (kille)","adjektiv som slutar på: a","Något du inte skulle vilja ha i julklapp (plural)","Något du säger när du blir arg","kroppsdel i best.form","")
var textStory_julspecial = "Klockan är halv sju på julaftonskvällen, familjen " + array_julspecial[0] + " kollar som vanligt på "+ array_julspecial[1] +" Pappa "+ array_julspecial[2] +" reser sig plötsligt upp och säger att han ska ut och köpa en " + array_julspecial[3] +". Rask tar han på sig "+ array_julspecial[4] +" och går ut. Familjen fortsätter kolla på tv:n och äter den traditionella "+ array_julspecial[5] + ". " + array_julspecial[6]+" "+ array_julspecial[7]+" senare kommer någon in innanför dörren, det är tomten. Familjen välkomnar honom och och han sätter sig ned på en/ett "+ array_julspecial[8]+" i vardagsrummet. Tomten börjar genast dela ut paket. Första namnet han ropar upp är "+ array_julspecial[9]+" åriga "+ array_julspecial[10] + ". Han rusar genast upp och hämtar sitt paket. Ivrig som han är öppnar han det direkt, när han öppnar det blir han förvånad, där i ligger nämligen flera " + array_julspecial[11] +" "+ array_julspecial[12] + ". " + array_julspecial[10] +" blir minst sagt förbannad och skriker ut "+ array_julspecial[13] + ". Han hoppar på tomten och slår honom i " + array_julspecial[14] + ". Kaos utbryter och tomten får fort ta av sig masken och visar sitt ansikte. Resten av kvällen får hela familjen förklara för lilla "+ array_julspecial[10]+", att tomten faktiskt inte finns på riktigt. Och det var den julen det för familjen " + array_julspecial[0]

var array_bankrån = arrayOf("Adjektiv som slutar på: a", "Siffra", "Tidsenhet","Siffra","Dåligt artistnamn","Superhjälte","Verb som slutar på: ar","Känt citat","Namn på hundvalp","Verb som slutar på: a","Kroppsdel","Skurk","Vapen i plural","Siffra","Tidsenhet","Siffra","Substantiv i plural","Substantiv i plural","Fordon som slutar på: n","Geografisk plats","Högtid","")
var textStory_bankrån = "Okej, det här är den " + array_bankrån[0] + "planen jag kom på, jag har arbetat med den i " + array_bankrån[1] + " " + array_bankrån[2] + "  så den kommer definitivt med " + array_bankrån[3] + " procent sannolikhet att fungera. " + array_bankrån[4] + " du klär ut dig till " + array_bankrån[5] + " , går in till banken, ställer dig på en stol och " + array_bankrån[6] + "  samtidigt som du skriker ut " + array_bankrån[7] +". Allt detta för att skapa en distraktion för " + array_bankrån[8] + "  vars uppgift är sno vaktens vapen, om du blir påkommen är planen att snabbt börja " + array_bankrån[9] + "  med vakten och under tiden köra in en spruta med sömnmedel i vaktens " + array_bankrån[10] + ". Då vakten är neutraliserad så kommer jag och " + array_bankrån[11] + " in, tar upp våra " + array_bankrån[12] + " och hotar bankpersonalen att ge oss koden till valvet. Vi har då exakt " + array_bankrån[13] + " " + array_bankrån[14] + " att ta oss in i och rensa valvet innan polisen kommer. Om någon inifrån banken försöker göra motstånd så har jag " + array_bankrån[15] + " " + array_bankrån[16] + " med mig som vi kan använda oss av för att stoppa potentiellt motstånd. Vi vill inte riskera att  använda våra " + array_bankrån[12] + "  om det inte är absolut nödsituation. Kom ihåg det är endast dom extremt värdefulla " + array_bankrån[17] + " som vi vill åt, inget annat.Vi springer sen ut bakvägen till " + array_bankrån[18] + "  och kör iväg, sedan delar vi upp oss och möts vid " + array_bankrån[19] + " så vi kan dela upp bytet. Det är planen och vi genomför den på " + array_bankrån[20] +"."

