package com.example.spens.mad_lib_design_2


val dejt_class = dejt()
val klass_class = klassatertraff()

var array_presskonferens = arrayOf("Namn på en tecknad figur", "Tidsenhet", "Beskrivning på en person","Siffra", "Mätenhet", "Färg","Siffra","Tidsenhet","Geografisk plats", "Substantiv", "Kroppsdel","Namn på känd person","Högtid","Årtal","Namn på känd plats", "Substantiv i singular", "Kroppsdel i bestämd form","Siffra","Historisk person", "Resturang", "Siffra","Tidsenhet","")
var textStory_presskonferens = "God kväll, jag heter " + array_presskonferens[0] + " och är huvudansvarig för denna mordutredning. Jag och mitt team har arbetat i många " + array_presskonferens[1] + " för att få fram en " + array_presskonferens[2] + " och bra beskrivning på mördaren. Det vi i nuläget vet är att mördaren antagligen är " + array_presskonferens[3] + "  " + array_presskonferens[4] + " lång, har " + array_presskonferens[5] + " hårfärg, är cirka " + array_presskonferens[6] + " "  + array_presskonferens[7] + " gammal, bor i " + array_presskonferens[8] + " och har av vittnen blivit sedd ha en " + array_presskonferens[9] + " hängandes kring sin " + array_presskonferens[10] + ". Vi har kommit fram till att mordet på " + array_presskonferens[11] + " ägt rum på " + array_presskonferens[12] + " " + array_presskonferens[13] + ". Brottet skedde i " + array_presskonferens[14] + ". Vapnet som mördaren ska ha använt var en/ett " + array_presskonferens[15] + ". Vapnet ska ha använts på så sätt att mördaren slog offret 10 gånger på " + array_presskonferens[16] + " vilket tillslut ledde till offrets död. Vi har just nu " + array_presskonferens[17] + " bevis som pekar på att brottet har begåtts av " + array_presskonferens[18] + ". Dock behöver vi ännu mer bevis för att vara säkra. Vi har ännu inte hittat brottslingen men enligt en trovärdig källa besöker mördaren " + array_presskonferens[19] + " " + array_presskonferens[20] + " gånger varje " + array_presskonferens[21] + ". Så vi räknar med ett gripande inom kort. Tack för mig!"


var array_jobbintervju = arrayOf(" Skådespelare","Namn på en historisk figur","Typ av arbete","Något du säger när du är i knipa","Typ av spel","Yrke man hade förr i tiden","Tidsspann","Namn på företag","Siffra","Valuta","Något du säger när du blir chockad","Adjektiv","Siffra"," Badrumsartikel i plural","Djur i plural","Typ av släkting","Namn","Siffra","Substantiv i plural","Siffra","Kroppsdel i bestämd form"," Tidsspan","Låt","")
var textStory_jobbintervju = "Intervjuare: " + array_jobbintervju[0] + " Jobbsökande " + array_jobbintervju[1]+ " Så... du vill alltså börja jobba som: " + array_jobbintervju[2] + " Vad har du för kvalifikationer för detta arbete? " + array_jobbintervju[3] + " Ehm, jag är väldigt bra på " + array_jobbintervju[4] +  ", jag har även jobbat som "+ array_jobbintervju[5] + " i " + array_jobbintervju[6] + ". Oj, ja det är väldigt bra meriter. Men varför vill du ta detta arbete. Jag vill ta jobbet för att jag är skyldig " + array_jobbintervju[7] + array_jobbintervju[8] + array_jobbintervju[9]+". " + array_jobbintervju[10] +" .Du är verkligen i en " + array_jobbintervju[11] + " knipa. Hur satte du dig i den positionen? Jag köpte " + array_jobbintervju[12] + array_jobbintervju[13] +" och jag köpte 10 000 " + array_jobbintervju[14]+" till min "+ array_jobbintervju[15]+ " " + array_jobbintervju[16] + ". Jaha, ja om du får detta jobb är din lön på en bra bit över "+ array_jobbintervju[17] +" "+ array_jobbintervju[18]+ " i månaden. Det borde täcka alla dina skulder. Jag måste som chef också informera dig om att ungefär " + array_jobbintervju[19] + " procent av de anställda skadar " + array_jobbintervju[20] + " varje år. Ser du detta som ett problem? Det är inget problem för mig, jag opererade bort den för " + array_jobbintervju[21] +" sedan. Okej, då är jobbet ditt, om du bara kan svara på en fråga till. Sjung en bit från låten " + array_jobbintervju[22] +". “Sjung”... Okej grattis du får jobbet!";


var array_julspecial = arrayOf("konstigt efternamn","film/serie","ovanligt namm","Substantiv i singular","klädesplagg","ovanlig maträt","siffra","tidsenhet","möbel","siffra","Tysk förnamn (kille)","adjektiv som slutar på: a","Något du inte skulle vilja ha i julklapp (plural)","Något du säger när du blir arg","kroppsdel i best.form","")
var textStory_julspecial = "Klockan är halv sju på julaftonskvällen, familjen " + array_julspecial[0] + " kollar som vanligt på "+ array_julspecial[1] +" Pappa "+ array_julspecial[2] +" reser sig plötsligt upp och säger att han ska ut och köpa en " + array_julspecial[3] +". Rask tar han på sig "+ array_julspecial[4] +" och går ut. Familjen fortsätter kolla på tv:n och äter den traditionella "+ array_julspecial[5] + ". " + array_julspecial[6]+" "+ array_julspecial[7]+" senare kommer någon in innanför dörren, det är tomten. Familjen välkomnar honom och och han sätter sig ned på en/ett "+ array_julspecial[8]+" i vardagsrummet. Tomten börjar genast dela ut paket. Första namnet han ropar upp är "+ array_julspecial[9]+" åriga "+ array_julspecial[10] + ". Han rusar genast upp och hämtar sitt paket. Ivrig som han är öppnar han det direkt, när han öppnar det blir han förvånad, där i ligger nämligen flera " + array_julspecial[11] +" "+ array_julspecial[12] + ". " + array_julspecial[10] +" blir minst sagt förbannad och skriker ut "+ array_julspecial[13] + ". Han hoppar på tomten och slår honom i " + array_julspecial[14] + ". Kaos utbryter och tomten får fort ta av sig masken och visar sitt ansikte. Resten av kvällen får hela familjen förklara för lilla "+ array_julspecial[10]+", att tomten faktiskt inte finns på riktigt. Och det var den julen det för familjen " + array_julspecial[0]

var array_bankrån = arrayOf("Adjektiv som slutar på: a", "Siffra", "Tidsenhet","Siffra","Dåligt artistnamn","Superhjälte","Verb som slutar på: ar","Känt citat","Namn på hundvalp","Verb som slutar på: a","Kroppsdel","Skurk","Vapen i plural","Siffra","Tidsenhet","Siffra","Substantiv i plural","Substantiv i plural","Fordon som slutar på: n","Geografisk plats","Högtid","")
var textStory_bankrån = "Okej, det här är den " + array_bankrån[0] + " planen jag kom på, jag har arbetat med den i " + array_bankrån[1] + " " + array_bankrån[2] + "  så den kommer definitivt med " + array_bankrån[3] + " procent sannolikhet att fungera. " + array_bankrån[4] + " du klär ut dig till " + array_bankrån[5] + " , går in till banken, ställer dig på en stol och " + array_bankrån[6] + "  samtidigt som du skriker ut " + array_bankrån[7] +". Allt detta för att skapa en distraktion för " + array_bankrån[8] + "  vars uppgift är sno vaktens vapen, om du blir påkommen är planen att snabbt börja " + array_bankrån[9] + "  med vakten och under tiden köra in en spruta med sömnmedel i vaktens " + array_bankrån[10] + ". Då vakten är neutraliserad så kommer jag och " + array_bankrån[11] + " in, tar upp våra " + array_bankrån[12] + " och hotar bankpersonalen att ge oss koden till valvet. Vi har då exakt " + array_bankrån[13] + " " + array_bankrån[14] + " att ta oss in i och rensa valvet innan polisen kommer. Om någon inifrån banken försöker göra motstånd så har jag " + array_bankrån[15] + " " + array_bankrån[16] + " med mig som vi kan använda oss av för att stoppa potentiellt motstånd. Vi vill inte riskera att  använda våra " + array_bankrån[12] + "  om det inte är absolut nödsituation. Kom ihåg det är endast dom extremt värdefulla " + array_bankrån[17] + " som vi vill åt, inget annat.Vi springer sen ut bakvägen till " + array_bankrån[18] + "  och kör iväg, sedan delar vi upp oss och möts vid " + array_bankrån[19] + " så vi kan dela upp bytet. Det är planen och vi genomför den på " + array_bankrån[20] +"."

var array_företagspitch = arrayOf("Namn", "Siffra","Grönsak på engelska", "Substantiv i singular","Verb","Butikskedja i plural","Land","Land","Siffra","Årtal","Hemsida","Namn på by","Låg siffra","Substantiv i plural","Hög siffra","Tidsenhet","Namn innehållande 3 boktsåver","Kändis","Kroppsdel i best form","Siffra","")
var textstory_företagspitch = "Hejsan jag heter " + array_företagspitch[0]+ " och står framför er här idag för att få en investering på " + array_företagspitch[1]+ " kronor. Min produk heter " + array_företagspitch[2]+ " och är en " + array_företagspitch[3]+ " som kan användas för att underlätta när man ska " + array_företagspitch[4]+ ". Just nu säljer vi vår produkt i alla " + array_företagspitch[5]+ " i " + array_företagspitch[6]+ " och ska utvidga oss till " + array_företagspitch[7]+ " nästa kvartal. Vi har totalt sett sålt " + array_företagspitch[8]+ " enheter sedan " + array_företagspitch[9]+ " då jag startade företaget. Några frågor? (Investerare) Ja jag har två frågor. Hur tänkte ni annonsera produkten? Och vad är er årliga omsättning och vinst? (" + array_företagspitch[0]+ ") Ja vi ska annonsera på hemsidor som exempelvis " + array_företagspitch[10]+ " och vi har även hyrt en anslagstavla i " + array_företagspitch[11]+ " där vi tror många kunder kommer lockas att köpa produkten. Våran omsättning förra året var på ca " + array_företagspitch[12]+ " kronor inklusive 44 st " + array_företagspitch[13]+ " men av lagliga skäl tog vi inte med det i våran årsredovisning. Vi gick minus " + array_företagspitch[14]+ " i vinst, alltså ingen vinst alls men vi är positiva ändå, jag tror att om ca 10 " + array_företagspitch[15]+ " kan vi ligga på plus minus noll och inom nolltid gå med vinst. (Investerare) Hur många anställda har företaget? (" + array_företagspitch[0]+ ") Just nu är det bara jag, min kompis " + array_företagspitch[16]+ " och faktiskt " + array_företagspitch[17]+ " , båda jobbar med produktionen, vet inte riktigt varför " + array_företagspitch[17]+ " jobbar hos oss men det är kul antar jag. Vi hade 200 anställda förra året men alla skadade " + array_företagspitch[18]+ " och fick sluta. På grund av detta är vi skyldiga ca " + array_företagspitch[19]+ " kronor till dessa människor, det är därför jag står här idag. Era pengar kommer nämligen gå åt till att försöka betala av, i alla fall en andel av skulden. (Investerare) Då tror jag vi är färdiga här, vi kommer återkomma inom 1 vecka om beslut, till dess ha en bra dag. Hejdå!"

var array_jakt = arrayOf("Påhittat långt namn","Adjektiv som slutar på: a","Litet djur i best form","Känd byggnad","siffra","Föremål som kan användas som vapen","Siffra","Barnleksak i plural","Fånigt smaknamn","Tidsenhet","Kroppsdel i best form","Siffra","Tidsenhet","Bakverk","Svordom ett barn skulle säga","Verb som slutar på: a","Något du säger när du blir förvånad","")
var textStory_jakt = "Hej och välkomna till jakt med " + array_jakt[0] +" idag ska vi jaga något speciellt, nämligen den ökända " + array_jakt[1] +" "+ array_jakt[2] +". Den har sitt näste precis här vid" + array_jakt[3]+ ". Det är ett mycket farligt och sällsynt djur, det finns bara "+ array_jakt[4] + " kvar idag. Bara ett vapen är till någon hjälp mot denna best och det är en "+ array_jakt[5] + ", om en nödsituation uppstår har vi "+ array_jakt[6] +" "+ array_jakt[7] + "lite utanför jaktområdet som är redo att användas mot "+ array_jakt[2] + " då det är så pass farligt. Många har försökt jaga det här monstret till varelse men misslyckats, min kompis "+ array_jakt[8] + " jagade i flera "+ array_jakt[9] + ", det var en tuff jakt och tillslut vann djuret, det slet av honom "+ array_jakt[10] + " och försvann sedan, varken "+ array_jakt[8] + " "+ array_jakt[10] + " eller djuret har setts till sen dess. Men det kommer inte hända mig, jag kommer mycket förberedd till den här utmaningen, har tränat i minst "+ array_jakt[11] + " "+ array_jakt[12] + ". Ska försöka lura in djuret i en fälla, den lever endast på "+ array_jakt[13] + " så jag kan använda det till min fördel genom att lägga ut bete och sedan lägga mig i bakhåll. "+ array_jakt[14] + "! här kommer ju den, rakt mot oss! Börja "+ array_jakt[15] + " då skrämmer du den så hämtar jag "+ array_jakt[5] + ". "+ array_jakt[16] + " jag tror jag glömde det hemma, ajdå..."


var array_reklam = arrayOf("Kroppsdel i best form","Något som äcklar dig","Föremål i ett hushåll i best form","Något annat som äcklar dig","Namn som låter adligt","Adjektiv","Möbel i best form","Verb","Substantiv i best form","Tidsspann","Typ av släkting","Adjektiv","Siffra","Valuta","Adjektiv","Låg siffra","Verb","Substantiv i plural","")
var textStory_reklam = "Trött på att alltid behöva använda " + array_reklam[0] + " när du ska torka bort " + array_reklam[1] + " fläckar från " + array_reklam[2] + "? Har du svårt att finna ro i vardagen för den där pölen med " + array_reklam[3] + " bara dyker upp och du vet inte hur man ska få bort den? Jag heter " + array_reklam[4] + " och presenterar " + array_reklam[5] + " Städarna. Vi hjälper dig att städa rent hela hushållet. Vill du bara ligga i " + array_reklam[6] + " och " + array_reklam[7] + " hela helgen istället för att ta fram " + array_reklam[8] + " och städa? Vi är lösningen! Det tar endast oss " + array_reklam[9] + " att genomföra en städning och just nu rengör vi också din " + array_reklam[10] + " så han eller hon är " + array_reklam[11] + " och ren. Allt detta för endast " + array_reklam[12] + " " + array_reklam[13] + " i timmen. Jag och mina kollegor jobbar dygnet runt för att kunden ska bli så " + array_reklam[14] + " som möjligt efter vi genomfört vårt arbete. " + array_reklam[15] + " procent av våra kunder är nöjda och beställer gärna våran tjänst igen. Så tveka inte, hör av dig till oss nu! Obs! Vi tar inget ansvar om din " + array_reklam[10] + " plötsligt börjar " + array_reklam[16] + " okontrollerat eller om " + array_reklam[17] + " plötsligt börjar försvinna från ert hem."

var array_dejt_p2 = arrayOf("Adjektiv","Verb","Resturang","Siffra","Längenhet","Adjektiv","Siffra","Substantiv i plural","Kroppsdel")
var array_dejt_p1 = arrayOf("Fordon i best form","Substantiv","Klädesplagg","Vätska","Adjektiv","Land","Star Wars karaktär","Substantiv","Tecknad figur")

var textStory_dejt = dejt_class.spelare1+ ": Hej! trevligt att träffas," + dejt_class.spelare2 + " var det va? Jag heter " + dejt_class.spelare1 + ", vad sägs som att gå in?\n" +
        dejt_class.spelare2 + ": Hej, ja det låter bra, förlåt om jag var lite sen, men på vägen till "+ array_dejt_p1[0] + " kom jag på att jag hade glömt min "+ array_dejt_p1[1] + ", och behöver verkligen den ikväll.\n " +
        dejt_class.spelare1+ ": Ingen fara, du ser väldigt "+ array_dejt_p2[0] + " ut ikväll! När jag väntade på dig passade jag på att "+ array_dejt_p2[1] + " lite för att få bort nerverna, är faktiskt lite nervös inför den här dejten.\n " +
        dejt_class.spelare2+ ": Jag är också lite nervös, men detta ska bli kul, köpte faktiskt den här "+ array_dejt_p1[2] + " bara för ikväll. Jag tycker vi går till restaurangen nu, börjar bli kallt här ute\n " +
        dejt_class.spelare1+ ": Ja självklart. Har bokat bord på "+ array_dejt_p2[2] + ", tänkte att vi skulle slå på stort ikväll. Det är inte så långt, ligger bara "+ array_dejt_p2[3]+ " " + array_dejt_p2[4] + " härifrån.\n" +
        dejt_class.spelare2+ ": Oj vilken fin restaurang, har aldrig varit här förut. Ska vi beställa något att dricka? Jag tar gärna ett glas "+ array_dejt_p1[3] + ".\n " +
        dejt_class.spelare1+ ": Det låter "+ array_dejt_p2[5] + ", tar nog också det. Så... berätta lite om dig själv? \n " +
        dejt_class.spelare2+ ": Jag kommer från "+ array_dejt_p1[5] + ", min pappa är "+ array_dejt_p1[6] + " men jag känner inte min mamma. Jag gillar att samla på "+ array_dejt_p1[7] + " och jobbar som assistent åt "+ array_dejt_p1[8] + ".\n" +
        "Person 1: Då har vi ett problem, jag har nämligen besöksförbud minst "+ array_dejt_p2[6] + " meter ifrån "+ array_dejt_p1[8] + " efter att jag kastade några "+ array_dejt_p2[7] + " och bröt "+ array_dejt_p2[8] + " på stackaren efter en dålig dejt vi hade. Så jag tror jag får lov att säga hejdå, detta kommer nog inte funka mellan oss. Hejdå"

var array_klass_p2 = arrayOf("Något du säger när du blir förvånad","Sjukdom","Namn","Typ av straff i plural","Påhittat jobb","Substantiv i best form","Siffra","Djur","Verb","Ovanlig fritidsaktivitet","")
var array_klass_p1 = arrayOf("Jobb ett barn skulle vilja ha","Siffra","Siffra","Namn på elak person","Adjektiv","Olaglig aktivitet","Elaktronisk pryl som slutar på: n","Verb","")

var textStory_klass = klass_class.spelare1 + ": Ne men " + array_klass_p2[0] + " hej på dig! Det var inte igår! \n " +
        klass_class.spelare2 +": Hej " + klass_class.spelare1 + " ne det var det inte, hur är det?\n " +
        klass_class.spelare1 +": Jo förutom att jag har fått " + array_klass_p2[1] + ", " + array_klass_p2[2] + " har gjort slut med mig och jag har fått " + array_klass_p2[3] + " så är allt bra. Själv?\n " +
        klass_class.spelare2 +": Ne allt är bra för mig, jag jobbar fortfarande som " + array_klass_p1[0] + ", är inne på mitt " + array_klass_p1[1] + "e år nu.\n "+
        klass_class.spelare1 +": Vad kul! Ne jag har fått nytt jobb som " + array_klass_p2[4] + ", det är inte jättekul men jag tjänar bra, vi har lite annat system där, lönen man får är " + array_klass_p2[5] + ".\n "+
        klass_class.spelare2 +": Ehm okej, ja det låter ju bra, jag och min partner har faktiskt skaffat barn, eller rättare sagt " + array_klass_p1[2] + " stycken, vårt senaste heter " + array_klass_p1[3] + " och är väldigt " + array_klass_p1[4] + ".\n" +
        klass_class.spelare1 +": Jaha vad kul! Själv har man ju bara sina " + array_klass_p2[6] + " stycken " + array_klass_p2[7] + " hemma, men så kan det va, hoppas man kan hitta någon trevlig person och " + array_klass_p2[8] + " på snart.\n"+
        klass_class.spelare2 +": Ja men det gör du nog! Kommer ihåg att du höll mycket på med " + array_klass_p1[5] + " på fritiden, gör du fortfarande det?\n"+
        klass_class.spelare1 +": Nja jag har slutat, har börjat att " + array_klass_p2[9] + ", det är ganska kul! Vad gör du när du får lite ledig tid?\n"+
        klass_class.spelare2 +": Jag sitter bara framför " + array_klass_p1[6] + " hela dagarna så inget intressant, men jag måste iväg nu och " + array_klass_p1[7] + " så vi får höras senare\n!"+
        klass_class.spelare1 + ": Okej ha det!"



var array_dialekter = arrayOf("Stockholm","Örebro","Malmö","Göteborg","Östergötland","Dalarna","Amerikansk brytning","Engelsk brytning","Tysk brytning","Italensk bryting")